platzigram/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('', include(('users.urls', 'users'), namespace='users')),
    
     
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
""" Posts URLs."""

from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),
    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='create'
    ),

     path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),

    path(
        route='posts/<int:pk>/comment/',
        view=views.CreateCommentView.as_view(),
        name ='comment'
    ),
     path(
        route='like_post/<int:pk>/',
        view=views.LikeView,
        name ='like_post'
    ),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


""" Post models. """
class Post(models.Model):
    """ Post model. """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = CloudinaryField('image')
    #photo = models.ImageField(upload_to='posts/photos')
    likes = models.ManyToManyField(User, related_name="posts")

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
   
    def __str__(self):
        return '{} by @{}'.format(self.title, self.user.username)


class Comment(models.Model):
    """ Post Comments """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

    text = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text
    
    

posts/forms.py
""" Post forms"""

from django import forms
from posts.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = {'user', 'profile', 'title', 'photo'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'user', 'profile', 'post', 'text'}

posts/views.py
# Django
from django.urls import  reverse_lazy, reverse
from django.views.generic import DetailView, ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

#Forms
from posts.forms import PostForm, CommentForm

# Models

from posts.models import Post, Comment

def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post.likes.add(request.user)
    return HttpResponseRedirect(reverse('posts:feed'))


class PostsFeedView(LoginRequiredMixin, ListView):
    """Return all published posts."""
    template_name = 'posts/feed.html'
    queryset = Post.objects.all()
    ordering = ('-created',)
    paginate_by = 30
    context_object_name = 'posts'


class PostDetailView(LoginRequiredMixin, DetailView):
    """Return post detail."""

    template_name = 'posts/detail.html'
    queryset = Post.objects.all()
    context_object_name = 'post'



class CreatePostView(LoginRequiredMixin, CreateView):
    """Create a ew Post"""
    template_name = 'posts/new.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        """Add user and prfile to context"""
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        context["profile"] = self.request.user.profile 
        return context


class CreateCommentView(LoginRequiredMixin, CreateView):
    # Create a ew Post
    template_name = 'posts/add_comment.html'
    form_class = CommentForm
    queryset = Post.objects.all()
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        # Add user and prfile to context
        context = super().get_context_data(**kwargs)
        context["post"] = self.get_object
        context["user"] = self.request.user
        context["profile"] = self.request.user.profile 

        return context

templates/posts/add_comment.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram | Comments</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">
            {% include "posts/post_card.html" %}

            <div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0">
                <form class="form-control" method="POST">
                {% csrf_token %}

                <input type="hidden" name="user" value="{{user.pk}}" />
                <input type ="hidden" name="profile" value="{{ profile.pk }}" />
                <input type="hidden" name="post" value ="{{post.pk}}"/>
                
                <div class="form-group">
                    <input name="text" type="text" class="form-control" placeholder="Comment">
                </div>
                <button class="btn btn-primary btn-block mt-5" type="submit" value="{{post}}">Add Comment</button>
            </form>
            </div>        
        </div>
    </div>
    
{% endblock %}

templates/posts/comment.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram | Comments</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">
            {% include "posts/post_card.html" %}

            <div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0">
                <form class="form-control" method="POST">
                {% csrf_token %}

                <input type="hidden" name="user" value="{{user.pk}}" />
                <input type ="hidden" name="profile" value="{{ profile.pk }}" />
                <input type="hidden" name="post" value ="{{post.pk}}"/>
                
                <div class="form-group">
                    <input name="text" type="text" class="form-control" placeholder="Comment">
                </div>
                <button class="btn btn-primary btn-block mt-5" type="submit" value="{{post}}">Add Comment</button>
            </form>
            </div>        
        </div>
    </div>
    
{% endblock %}

templates/posts/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram | Detail</title>
{% endblock%}

{% block container %}

    <div class="container">
        <div class="row">
            {% include "posts/post_card.html" %}
        </div>
    </div>

{% endblock %}

templates/posts/display_comment.html
<!-- Comments to post -->
    {% for comment in post.comments.all %}
        <div class="ml-2 mt-0 mb-2 comment-box">
            <div class="container user-comment-box">
            <h6 class="comment-user"> 
                <b>
                    <a href="{% url "users:detail" comment.user.username %}">
                        <img class="mr-3 rounded-circle" height="35" width="35" src="{{ comment.profile.picture.url }}" alt="{{ comment.user.get_full_name }}">
                    {{comment.user}}
                    </a>
                </b>
            </h6>
                <p>{{ comment.text }}</p>
            </div>
        </div>

    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}
     <p class="ml-2 mt-0 mb-2">
    <a href="{%url 'posts:comment' post.pk%}">Add comment</a>
    </p>
    

templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">

            {% for post in posts %}
            <div class="col-sm-12 col-md-8 offset-md-2 mt-3 p-0 post-container">
                <div class="media pt-3 pl-3 pb-1">
                    <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
                    <div class="media-body">
                        <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
                    </div>
                </div>
                <div class="text-center">
                
                    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
                
                </div>
                


                <p class="mt-1 ml-2" >
                    <a href="" style="color: #000; font-size: 20px;">
                        <i class="far fa-heart"></i>
                    </a> 30 likes
                </p>
                <p class="ml-2 mt-0 mb-2">
                    <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/posts/new.html
{% extends "base.html" %} {% block head_content %}
<title>Create new post</title>
{% endblock %} 

{% block container %}

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-12 pt-3 pb-3" id="profile-box">
      <h4 class="mb-4">Post a new photo!</h4>

      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <input type="hidden" name="user" value="{{ user.pk}}" />
        <input type="hidden" name="profile" value="{{ profile.pk }}" />

        {# Website field #}
        <div class="form-group">
          <input
            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
            type="text"
            name="title"
            placeholder="Title"
          />
          <div class="invalid-feedback">
            {% for error in form.title.errors %}{{ error }}{% endfor %}
          </div>
        </div>

        {# Photo field #}
        <div class="form-group">
          <label>Choose your photo:</label>
          <input
            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
            type="file"
            name="photo"
            placeholder="photo"
          />
          <div class="invalid-feedback">
            {% for error in form.photo.errors %}{{ error }}{% endfor %}
          </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block mt-5">
          Publish!
        </button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/posts/pagination.html
    <nav>
        <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
            </li>
        {%endif%}
            <li class="page-item">
                <a href="#" class="page-link"> {{page_obj.number}} of {{page_obj.paginator.num_pages}}</a>
            </li>
        {%if page_obj.has_next%}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
            </li>
        {%endif%}
        </ul>
    </nav>

templates/posts/post_card.html
<!--Post title -->
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url "users:detail" post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" width="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>

    <!-- Post Image -->
    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">

    <!-- Posts Details -->
    <p class="mt-1 ml-2" >
        <form action="{%url 'posts:like_post' post.pk %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-light like-btn" type="submit", name="post_id" value="{{post.id}}"><i class="far fa-heart"></i></button>
            {{post.likes.count}}
        </form>
        
    </p>
    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>
    <!-- import coments section -->
    {%include 'posts/display_comment.html'%}
</div>