platzigram/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('', include(('users.urls', 'users'), namespace='users')),
    
     
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
""" Posts URLs."""

from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),
    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='create'
    ),

     path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),

    path(
        route='posts/<int:pk>/comment/',
        view=views.CreateCommentView.as_view(),
        name ='comment'
    ),
     path(
        route='like_post/<int:pk>/',
        view=views.LikeView,
        name ='like_post'
    ),
]

users/urls.py
# Django
from django.urls import path

# View
from users import views


urlpatterns = [
    # Management
    path(
        route='users/login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='users/logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='users/signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='users/me/profile/',
        view=views.UpdateProfile.as_view(),
        name='update_profile'
    ),

    # Posts
    path(
        route='profile/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
  

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">   
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
    {% include "nav.html" %}
    
    <div class="container mt-5">
        {% block container %}
        {% endblock %}
    </div>

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-white navbar-custom" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed'%}">
            <img src="{% static "img/instagram.png" %}" height="45" width="45px" class="d-inline-block align-top"/>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav" >
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{%url 'users:detail' request.user.username %}">
                    {%if request.user.profile.picture %}
                        <img src="{{request.user.profile.picture.url}}" height="35" width="35"class="d-inline-block align-top rounded-circle"/>
                    
                    {% else %}
                         <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                    {%endif%}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create'%}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "users:logout" %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>