platzigram/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('', include(('users.urls', 'users'), namespace='users')),
    
     
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
""" Posts URLs."""

from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),
    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='create'
    ),

     path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),

    path(
        route='posts/<int:pk>/comment/',
        view=views.CreateCommentView.as_view(),
        name ='comment'
    ),
     path(
        route='like_post/<int:pk>/',
        view=views.LikeView,
        name ='like_post'
    ),
]

users/urls.py
# Django
from django.urls import path

# View
from users import views


urlpatterns = [
    # Management
    path(
        route='users/login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='users/logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='users/signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='users/me/profile/',
        view=views.UpdateProfile.as_view(),
        name='update_profile'
    ),

    # Posts
    path(
        route='profile/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
  

]

users/models.py
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Django
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    #picture =models.ImageField(upload_to='users/pictures', blank=True, null=True)
    picture = CloudinaryField('image')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

users/forms.py
# Django imports
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    # Sign up Form.
    username = forms.CharField(max_length=50, min_length=4)

    password = forms.CharField(max_length=70, widget=forms.PasswordInput)
    password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput)
   
    first_name = forms.CharField(max_length=50, min_length=2)
    last_name = forms.CharField(max_length=50, min_length=2)
   
    email = forms.CharField(max_length=70, min_length=6, widget=forms.EmailInput)

    def clean_username(self):
        # usernamemust be unique.
        username = self.cleaned_data['username']
        query = User.objects.filter(username=username).exists()

        if query:
            raise forms.ValidationError('Username is already in use')
        return username

    def clean(self):
        # verify password confirmation match

        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Password does not match')

        return data

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.views.generic import DetailView, FormView, UpdateView
from django.urls import reverse, reverse_lazy

# Models
from django.contrib.auth.models import User
from users.models import Profile
from posts.models import Post

# Forms
from users.forms import SignupForm


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

class SignupView(FormView):
    """ Users sign up view """
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """saver data"""
        form.save()
        return super().form_valid(form)

class UpdateProfile(LoginRequiredMixin, UpdateView):
    """Update profile view"""
    template_name = 'users/update_profile.html'
    model = Profile
    fields= ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        """Return users profile"""
        return self.request.user.profile

    def get_success_url(self):
        """return to users profile"""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})


class LoginView(auth_views.LoginView):
    """Login view"""
    template_name =  'users/login.html'
    

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""
    template_name = 'users/logout.html'

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% load static %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <!-- Icons -->
    <script src="https://kit.fontawesome.com/fe2d316c26.js" crossorigin="anonymous"></script>
</head>
<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{user.username}}" class="rounded-circle" width="150px" height="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update_profile" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>
       <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url "posts:detail" post.pk %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends 'users/base.html' %}
{% block head_content %}
    <title>Platzigram sign in</title>
{% endblock %}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif %}
    <form method="POST" action='{% url "users:login" %}'>
        {% csrf_token %}
    <div class="form-group">
        <input class="form-control" type="text" placeholder="Username" name="username">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" placeholder="Password"  name ="password">
    </div>

    
    <button class="btn btn-primary btn-block mt-5"type="submit">Sign in</button>


    </form>
    <p class="mt-4">Don't have an account yet? <a href="{% url 'users:signup'%}">Sign up here.</a></p>

{% endblock %}

templates/users/signup.html
{% extends 'users/base.html' %}

{% block head_content %}
<title>Platzigram | Sign up</title>

{% endblock %}

{% block container %}
   
    <form method="POST" action='{% url "users:signup" %}'>
        {% csrf_token %}
        
        {{ form.as_p}}

        <button class="btn btn-primary btn-block mt-5"type="submit">Register</button>
    </form>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-lg-6 col-xs-12 p-4" id="profile-box">

            <form action="{%url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% if form.errors%}
                    <p class="alert alert-danger">{{form.errors}}</p>
                {%endif%}
                
                <div class='media'>
                {%if profile.picture %}
                    <img src="{{profile.picture.url}}" class="rounded-circle" height="50" width="50"/>
                {%else%}
                    <img src="" class="rounded-circle" height="50" width="50"/>
                {%endif%}  
                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{user.get_full_name}}</h5>
                        <p class="ml-4"><input type="file" name="picture" required="true"></p>
                    </div>
                </div>

                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input class="form-control" type="url" name="website" placeholder="Website" value="{{profile.website}}"/>
                </div>
            
                <div class="form-group">
                    <label>Biography</label>
                    <textarea class="form-control" name="biography">{{ profile.biography }}</textarea>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{{ profile.phone_number }}"
                    />
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}